const prompt = require('prompt-sync')({sigint: true});

const hat = '^';
const hole = 'O';
const fieldCharacter = '░';
const pathCharacter = '*';
const moves = ['w', 'a', 's', 'd'];

class Field {
  constructor(fieldArray) {
    this._fieldArray = fieldArray;
    this._currentRow = 0;
    this._currentColumn = 0;
    // _currentRow and _currentColumn keep track of the player's current position on the field
  }

  get fieldArray() {
    return this._fieldArray;
  }

  print() {
    for (let i = 0; i < this.fieldArray.length; i++) {
      console.log(this.fieldArray[i].join(''));
    }
  }

  get currentRow() {
    return this._currentRow;
  }

  get currentColumn() {
    return this._currentColumn;
  }

  set currentRow(newRow) {
    this._currentRow = newRow;
  }

  set currentColumn(newColumn) {
    this._currentColumn = newColumn;
  }

  moveUp() {
    this.currentRow -= 1;
  }

  moveLeft() {
    this.currentColumn -= 1;
  }

  moveDown() {
    this.currentRow += 1;
  }

  moveRight() {
    this.currentColumn += 1;
  }

  // promptPlayer(), when called, prints the current state of the game and prompts the player for a move. Invalid moves are disregarded and the player prompted again.
  promptPlayer() {
    this.print();
    this.move = prompt('\nWhich way? [w (up), a (left), s (down), d (right)] ');
    if (!moves.includes(this.move)) {
      console.log('Invalid move. Please try again.');
      this.promptPlayer();
    }
  }

  static generateField() {
    // Generates random field with random width and height (between 5 and 10), and a random percentage of holes (between 20 and 25 percent).
    const fieldHeight = Math.floor(Math.random() * 5) + 6;
    const fieldWidth = Math.floor(Math.random() * 5) + 6;
    const holePercentage = Math.floor(Math.random() * 5) + 21;

    const generatedField = [];

    // populates the fieldArray with rows
    for (let i = 0; i < fieldHeight; i++) {
      generatedField.push([]);
    }

    // populates the fieldArray with columns
    for (let i = 0; i < fieldHeight; i++) {
      for (let j = 0; j < fieldWidth; j++) {
        generatedField[i].push(fieldCharacter);
      }
    }

    // places the start point at the top-most left
    generatedField[0].splice(0, 1, pathCharacter);

    // places hat at random location
    // The '-1' and '+1' prevent array reference errors and ensures we do not accidentally place hat at starting position respectively.
    const randomRow = Math.floor(Math.random() * (fieldHeight - 1)) + 1;
    const randomColumn = Math.floor(Math.random() * (fieldWidth - 1)) + 1;
    generatedField[randomRow].splice(randomColumn, 1, hat);

    const numOfHoles = Math.floor((holePercentage / 100) * fieldHeight * fieldWidth);

    // places holes in random locations
    for (let k = 0; k < numOfHoles; k++) {
      const randomRow = Math.floor(Math.random() * fieldHeight);
      const randomColumn = Math.floor(Math.random() * fieldWidth);

      if (generatedField[randomRow][randomColumn] !== pathCharacter && generatedField[randomRow][randomColumn] !== hat && generatedField[randomRow][randomColumn] !== hole) {
      generatedField[randomRow].splice(randomColumn, 1, hole);
      }
    }

    return generatedField;
  }
}

// The play function. It takes in a field instance (randomly generated by static generateField()) and guides the player through the game.
const play = (field) => {
  console.log('Find Your Hat (^). Avoid the holes (O). Stay within the field (░). One can use ctrl+C to break.\n');

  // The while statement ensures the game cycles until the player wins (finds the hat) or loses (falls out of the field or into a hole).
  while (field.fieldArray[field.currentRow][field.currentColumn] !== hat) {
    field.promptPlayer();

    switch (field.move) {
      case 'w':
        field.moveUp();
        break;
      case 'a':
        field.moveLeft();
        break;
      case 's':
        field.moveDown();
        break;
      case 'd':
        field.moveRight();
        break;
    }

    if (field.fieldArray[field.currentRow] === undefined || field.fieldArray[field.currentRow][field.currentColumn] === undefined) {
      console.log('Oopsie daisie. You fell out of the field. Please try again.\n');
      break;
    } 
    else if (field.fieldArray[field.currentRow][field.currentColumn] === hole) {
      console.log('Fiddlesticks! You fell into a hole. Please try again.\n');
      break;
    }
    else if (field.fieldArray[field.currentRow][field.currentColumn] === fieldCharacter) {
      field.fieldArray[field.currentRow].splice(field.currentColumn, 1, pathCharacter);
    }
  }

  if (field.fieldArray[field.currentRow][field.currentColumn] === hat) {
    field.fieldArray[field.currentRow].splice(field.currentColumn, 1, pathCharacter);
    field.print();
    console.log('\nCongratulations! You found your hat.')
  }
}

// When the file is run on Node.js, a random field will be generated, used to create a field object and the player prompted to play.
const playFieldArray = Field.generateField();
const playField = new Field(playFieldArray);
play(playField);